界面:
  标题: "跌倒检测系统"
  组件:
    - 类型: "图片显示"
      路径: "runs/detect" # 修改这里！现在只指定到 runs/detect 这一层
      刷新频率: 100 # 毫秒，前端刷新图片的间隔。与 detect.py 的 60 帧间隔（约 2 秒）匹配。
      最大宽度: 800 # 像素
    - 类型: "状态文本"
      内容: "系统运行中..."
